config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'
  devise_for :users
  get 'user/:id', to: 'user#show' , as: 'user_show'
  get 'users', to: 'user#index' ,as:'users'
  # get '/recipes', to: 'recipes#index'
  # get '/recipe/new', to: 'recipes#create', as: 'new_recipe' #new so verb ni get
  # post '/recipes', to: 'recipes#create' ,as: 'store_recipe'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
  # get '/recipes/id', to: 'recipe#show', as: 'show_recipe'
  # delete '/recipe/:id' , to: 'recipes#destroy', as: 'drop_recipe'

  # resouce method
  resources :recipes do #saves time .. rather than typin it all .. all indivigual routes just write this
    member do
      post 'like'
    end
  end
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    # relatonship to user class 
    belongs_to :user
    has_many :likes , dependent: :destroy
    has_many :recipe_styles ,  dependent: :destroy#delete the relationship at the joining table
    has_many :styles, through: :recipe_styles 
    has_many :recipe_ingredients  ,  dependent: :destroy
    has_many :ingredients, through: :recipe_ingredients
    validates :user_id, presence: true
    validates :name, presence: true, length: { minimum: 5, maximum: 100 }
    validates :summary, presence: true, length:{minimum:10, maximum: 150}
    validates :description, presence: true, length: {minimum:20 , maximum:500 }
    mount_uploader :picture, PictureUploader  #Added after uploader
    validate :picture_size
    #this is instruct active record how to pick,. the creteria
    default_scope -> {order(updated_at: :desc)} #this would tell the active record to pick the recordsd in order of date of udate, in desc order
    def thumbs_up_counter
        self.likes.where(like: true).size
    end
    def thumbs_down_counter
        self.likes.where(like: false).size
    end
    private
        def picture_size
            if picture.size>5.megabytes
                errors.add(:picture, "The picture is too big.. shuld be less than 5MB")                
            end
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only:[:update,:edit,:show,:like] #to eliminate @recipe= Recipe.find(id)
   before_action :require_login, except:[:show,:index]
   before_action :require_same_user , only:[:edit,:update] #specify the actrion
   before_action :admin_user, only: :destroy
   # protect_from_forgery

# Rails automaticaly loads the page name that matches with the function
 def index
    # @recipes = Recipe.all.sort_by{|likes| likes.thumbs_up_counter}.reverse #would sort the recipes in descending order of number of likes
    #to impelement the pagination Gem
    @recipes = Recipe.paginate(page: params[:page],per_page: 4) #will impelemn will paginate-> the last part ie the per page is optional
 end   

 def show #we can use "bindings.pry" to puth the server on hold, 
     #view the parameters on the url, the use  "params[whatever: ,whtaever:]"    
 end
 #the "new" method willl be used to mass assighn , a new rercipe,, it will do this vua the recipe params method,,
#  the recipe params method on the other hand only allows :name :summary and :description yo pass through
 def new
    @recipe = Recipe.new #we do not pass anything to the init..
 end
 def create
    #  binding.pry #to chck the parameters bieng passed to the method usin it makes the server completley freeze
    @recipe = Recipe.new(recipe_params)#pass the variable from the "recipe_params" method 
    @recipe.user = current_user
    if @recipe.save #if save was succesfull
        flash[:success]="Your recipe Creation was succesfull"
        redirect_to recipes_path
        #return home
    else
        render :new
    end
 end
 def edit
    
 end
 def update 
     
     if @recipe.update(recipe_params)
        flash[:success]= "Your Recipe has been updated"
        redirect_to recipes_path(@recipe)
     else
        render :edit
     end
 end
 def like  
    @like=Like.create(like: params[:like], user: User.first, recipe: @recipe ) #use the relationships GODDAMNIT
    if @like.save #if save was succesfull
      flash[:info]="Your like was recorded"
      redirect_back fallback_location: root_path
      #return home
  else
   flash[:danger]="Youve already Voted For this Recipe"
   redirect_back fallback_location: root_path
  end
end
def destroy
   Recipe.find(params[:id]).destroy
   flash[:success] = "Deleted succesfully"
   redirect_to recipes_path
end
 private #private methods
    def recipe_params # :recipe is the top most object
        params.require(:recipe).permit(:name,:summary,:description, :picture ,style_ids:[],ingredient_ids: []) #its called frst to check/ filter the vars to be passed to create
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:id])    
    end
    def require_same_user
      if current_user != @recipe.user && !current_user.admin
         flash[:danger]='You can only edit your own recipes'
         redirect_back fallback_location: root_path
      else
      end
      
    end
    def admin_user
      redirect_to recipes_path unless current_user.admin?
   end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %> 
<div class= "row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for( @recipe, html: {multipart: true}) do |f|%> <%#the 'html:' symbol was aadedd after image upload feaat was active%>
            <%=f.label :name%>
            <%=f.text_field :name%>
            
            <%=f.label :summary%>
            <%=f.text_field :summary%>
            
            <%=f.label :description%>
            <%=f.text_area :description, rows: 10 %>

            <strong> Styles : </strong>
            <%= f.collection_check_boxes :style_ids, Style.all,:id,:name do |sc|%>
                <% sc.label( class: 'checkbox-inline input_checkbox') {sc.check_box(class: 'checkbox') }+sc.text %>
            <% end %>
            <br/><br/>
            <strong> Ingredients : </strong>
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all,:id,:name do |ic|%>
                <% ic.label( class: 'checkbox-inline input_checkbox') {ic.check_box(class: 'checkbox') }+ic.text %>
            <% end %>
            <br/><br/>
            <span class="picture">
                <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png'%>  <%# the 'acccept:' shows the kinnd of images that can be accepted %>
            </span>

            <%=f.submit(@recipe.new_record? ? 'Create Recipe': 'Edit Recipe', class: "btn btn-success")%> <%# Be make sure not to forget the second"?" "%>
        <%end%>
    </div>
</div>
<%# this is tpo handle page size %>
<script type="text/javascript">
    $('#recipe_picture').bind('change',function() {
        size_in_megabytes = this.files[0].size/1024/1024;
        if(size_in_megabytes > 5){
            alert('Maximum file size  is 5MB please choose a smaller file');
        }
    });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe"%>
<%= render 'form'%>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes"%>
<div class="row">
    <ul class="nav nav-tabs">
        <li class= "active">
            <%= link_to "Recipes",recipes_path%>
        </li>
        <li>
            <%= link_to "Chefs", users_path%>
        </li>
    </ul>
    <div class= "col-md-4 col-md-offset-4 center">
            <%= will_paginate%>
        </div>
</div>
<hr/>
<%@recipes.each do |recipe|%>
    <div class ="row">
        <div class="col-md-2 grav">
            <section class= "user_info center ">
                <%=link_to gravatar_for(recipe.user, size:100),user_show_path(recipe.user)  %>
                <h5> User Name: <%=recipe.user.name%> </h5>
            </section>
        </div> 
        <div class="col-lg-6 well">
            <h4><%= link_to recipe.name,recipe_path(recipe) %> </h4>
            <p><%=  recipe.summary %> </p>
            <p>
                <span class= "quiet">
                    <small>
                       Created :  <%= time_ago_in_words(recipe.created_at)%> ago &nbsp 
                    </small>
                </span>
                 <span class= "quiet">
                    <small style="color:green;">
                        Updated : <%= time_ago_in_words(recipe.updated_at)%> ago 
                    </small>
                </span>
            </p> 
                <div class= "col-sm-7">
                <%# <to offset thte others> %>
                </div>
                &nbsp
                <div class= "col-sm-2">
                    <%= button_to [:like, recipe,like: true],style: "background-color: transparent;border: transparent;" do %>
                        <i class = "glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_counter%>
                    <% end  %>
                </div>
                    &nbsp&nbsp&nbsp
                <div class = "col-sm-2">
                    <%= button_to [:like, recipe, like: false],style: "background-color: transparent;border: transparent;" do %>
                        <i class = "glyphicon glyphicon-thumbs-down"></i>&nbsp  <%= recipe.thumbs_down_counter%>
                     <% end %>
                </div>               
          
         </div>
        <div class="col-md-2  ">
        
            <%= link_to image_tag(recipe.picture.url, size: "250x150", class: "gravatar") , recipe_path(recipe) if recipe.picture?%>
        </div> 
    </div>
    <hr/>
<% end %>
<%= will_paginate%>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create New Recipe"%>

<%= render 'form'%>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class= "row">
    <div class= "col-md-4 pull-right center ">
    <%= link_to gravatar_for(@recipe.user, size: 200), user_show_path(@recipe.user)%>
    <p>
        <h5>
            Brought to you by : <%= @recipe.user.name%>
        </h5>
    </p>
    </div>
  
    <div class= "col-md-8"> 
        <div class="pull-right">
            <% if current_user && current_user == @recipe.user || current_user && current_user.admin? %>
                <%= link_to edit_recipe_path, class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                Edit this Recipe<i class=" glyphicon glyphicon-pencil" style="color:white;"></i>
                <% end %>
            <% end %>
            <% if current_user && current_user.admin? %>
                <%= button_to recipe_path(@recipe), class:"btn  btn-small btn-danger ", style: "border-color: red; width:100%; margin-top: 20px;", method: :delete, data: {confirm: "Are You sure"} do%>
                 Delete<i class=" glyphicon glyphicon-trash" style="color:white;"></i>
                <% end %>
            <% end %>
        </div>
        
        <h3> <%= @recipe.summary %> </h3>
    <div class="show_recipe">
        <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture?%>
    </div>
        <div class= "well">
            <% if @recipe.styles.any? %>
                <p>Style:<%= render @recipe.styles%></p>
            <% end %>
            <% if @recipe.ingredients.any? %>
                <p>Ingredients: <%= render @recipe.ingredients %></p>
            <% end %>
            <p> 
                <strong>Steps:</strong>
            </p>
            <%= simple_format(@recipe.description) %>
                <div class= "col-sm-7">
                <%# <to offset thte others> %>
                </div>
                &nbsp
                <div class= "col-sm-2">
                    <%= button_to [:like, @recipe,like: true],style: "background-color: transparent;border: transparent;" do %>
                        <i class = "glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @recipe.thumbs_up_counter%>
                    <% end  %>
                </div>
                    &nbsp&nbsp&nbsp
                <div class = "col-sm-2">
                    <%= button_to [:like, @recipe, like: false],style: "background-color: transparent;border: transparent;" do %>
                        <i class = "glyphicon glyphicon-thumbs-down"></i>&nbsp  <%= @recipe.thumbs_down_counter%>
                     <% end %>
                </div>
                
            
                          
        </div>
    </div>
</div>
<h5> <%= link_to 'Back',recipes_path, class: "btn btn-warning btn-small"%></h5>