config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'
  devise_for :users
  get 'user/:id', to: 'user#show' , as: 'user_show'
  get 'users', to: 'user#index' ,as:'users'
  # get '/recipes', to: 'recipes#index'
  # get '/recipe/new', to: 'recipes#create', as: 'new_recipe' #new so verb ni get
  # post '/recipes', to: 'recipes#create' ,as: 'store_recipe'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
  # get '/recipes/id', to: 'recipe#show', as: 'show_recipe'
  # delete '/recipe/:id' , to: 'recipes#destroy', as: 'drop_recipe'

  # resouce method
  resources :recipes do #saves time .. rather than typin it all .. all indivigual routes just write this
    member do
      post 'like'
    end
  end
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if notice != nil || alert != nil%>
 <div class="row">   
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class= "row">
    <div class ="alert alert-danger col-md-8 col-md-offset-2">
        <h5> Please Correct the following errors</h5>
        <ul>
            <% obj.errors.full_messages.each do |msg|%>
                <li><%=msg%> </li>
            <%end%>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">    
    <div >
      &copy;Jeff made with Ruby  <a href="" target="">S.Footer</a> ..... for a better Expirience.
    </div>
  </div>
</footer>

app/views/shared/_guestnav.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-fixed-top " >

  <div class="container">
      <%= link_to "Home",root_path, class: "bt  btn-lg btn-success" ,id:"logo"%>
     <div class= 'nav_item'>
        <div class="dropdown">
          <span>            
            <%= link_to '#', class:'btn btn-default btn-success dropdown-toggle', 'data-toggle'=>'dropdown' do%>
              <i class='glyphicon glyphicon-apple' style="color:white;"></i>
              Styles : <b class='caret'></b >
            <%end %>
          </span>
          <div class="dropdown-content " , style= 'margin-top:5px; border:thin;  '>
            
              <% Style.all.each do |style|%>
                
                  <p > 
                    <%= link_to  style_path(style), class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    <%= style.name%> <i class="glyphicon glyphicon-grain" style="color:white;"></i>
                    <% end %>
                  </p>
               
              <% end %>           
           
          </div>
        </div>
      </div>
      <div class= 'nav_item'>
        <div class="dropdown">
          <span>            
            <%= link_to '#', class:'btn btn-default btn-success dropdown-toggle', 'data-toggle'=>'dropdown' do%>
              <i class='glyphicon glyphicon-grain' style="color:white;"></i>
              Ingredients : <b class='caret'></b >
            <%end %>
          </span>
          <div class="dropdown-content " , style= 'margin-top:5px; border:thin;'>
          
              <% Ingredient.all.each do |ingredient|%>
                
                  <p > 
                    <%= link_to  ingredient_path(ingredient), class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    <%=ingredient.name%> <i class="glyphicon glyphicon-leaf" style="color:white;"></i>
                    <% end %>
                  </p>
                              
              <% end %>           
           
          </div>
      </div>
      </div>
  <div class= "pull-right">
    <div class="nav_item">
        <%= link_to "Log In",new_user_session_path, class:" btn btn-default btn-warning" %> <%#we are not certain if we need to pass the current user.. or ust kavu%>
    </div>
     <div class="nav_item"> 
      <p><%= link_to "Register", new_user_registration_path, data: { confirm: "Are you sure?" },class: 'btn btn-warning btn-default' %></p>
    </div>
  </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<div class= "row">
    <div class = "col ">
        <% flash.each do |message_type, message| %>
            <div class = "alert alert-<%= message_type%>"><%= message%>
                <a class= "close" data-dismiss="alert"> &#215</a>
            </div>
        <%end%>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-fixed-top " >
  <div class="container">
    <%= link_to "Recipes",recipes_path(current_user), class: "bt  btn-lg btn-success" ,id:"logo"%>
    
      <div class= 'nav_item'>
        <div class="dropdown">
          <span>            
            <%= link_to '#', class:'btn btn-default btn-success dropdown-toggle', 'data-toggle'=>'dropdown' do%>
              <i class='glyphicon glyphicon-apple' style="color:white;"></i>
              Styles : <b class='caret'></b >
            <%end %>
          </span>
          <div class="dropdown-content " , style= 'margin-top:5px; border:thin;  '>
            
              <% Style.all.each do |style|%>
                
                  <p > 
                    <%= link_to  style_path(style), class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    <%= style.name%> <i class="glyphicon glyphicon-grain" style="color:white;"></i>
                    <% end %>
                  </p>           
              <% end %> 
              <% if current_user %>
                <hr/>
                <%= link_to  new_style_path, class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    New Style<i class="glyphicon glyphicon-pencil" style="color:white;"></i>
                    <% end %>
              <% end %>          
           
          </div>
        </div>
      </div>
      <div class= 'nav_item'>
        <div class="dropdown">
          <span>            
            <%= link_to '#', class:'btn btn-default btn-success dropdown-toggle', 'data-toggle'=>'dropdown' do%>
              <i class='glyphicon glyphicon-grain' style="color:white;"></i>
              Ingredients : <b class='caret'></b >
            <%end %>
          </span>
          <div class="dropdown-content " , style= 'margin-top:5px; border:thin;'>          
              <% Ingredient.all.each do |ingredient|%>                
                  <p > 
                    <%= link_to  ingredient_path(ingredient), class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    <%=ingredient.name%> <i class="glyphicon glyphicon-leaf" style="color:white;"></i>
                    <% end %>
                  </p>                              
              <% end %>
               <% if current_user %>
                <hr/>
                <%= link_to  new_ingredient_path, class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    New Ingredients <i class="glyphicon glyphicon-pencil" style="color:white;"></i>
                    <% end %>
              <% end %>             
          </div>
      </div>
      </div>
     <div class="pull-right">
      <div class= 'nav_item'>
        <div class="dropdown">
          <span>            
            <%= link_to '#', class:'btn btn-default btn-danger dropdown-toggle', 'data-toggle'=>'dropdown' do%>
              <i class='glyphicon glyphicon-user' style="color:white;"></i>
              <%=current_user.name%><b class='caret'></b >
            <%end %>
          </span>
          <div class="dropdown-content " , style= 'right: 0; margin-top:5px; border:thin;'>
            
               <p >
                  <%= link_to  new_recipe_path, class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    New Recipe <i class="glyphicon glyphicon-cutlery" style="color:white;"></i>
                 <% end %>
              </p>
              <hr/>        
               <p >
                  <%= link_to  user_show_path(current_user), class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    View Profile <i class=" glyphicon glyphicon-eye-open" style="color:white;"></i>
                 <% end %>
              </p>
              <p >
                  <%= link_to  edit_user_registration_path, class:"btn  btn-small btn-success ", style: "border-color: green;" do%>
                    Edit Profile <i class=" glyphicon glyphicon-pencil" style="color:white;"></i>
                 <% end %>
              </p>
              <hr/>
              <p>
                <%= button_to destroy_user_session_path ,class: 'btn btn-danger btn-small',method: :delete do%>
                  Log Out<i class=" glyphicon glyphicon-off" style="color:white;"></i>
                <% end %>
          </div>
      </div>
          
    </div>
    
  </div>
</nav>


  

app/views/shared/_page_title.html.erb
<p>
    <h1> <%= title %> </h1>
    <hr/>
</p>