config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'
  devise_for :users
  get 'user/:id', to: 'user#show' , as: 'user_show'
  get 'users', to: 'user#index' ,as:'users'
  # get '/recipes', to: 'recipes#index'
  # get '/recipe/new', to: 'recipes#create', as: 'new_recipe' #new so verb ni get
  # post '/recipes', to: 'recipes#create' ,as: 'store_recipe'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
  # get '/recipes/id', to: 'recipe#show', as: 'show_recipe'
  # delete '/recipe/:id' , to: 'recipes#destroy', as: 'drop_recipe'

  # resouce method
  resources :recipes do #saves time .. rather than typin it all .. all indivigual routes just write this
    member do
      post 'like'
    end
  end
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save{self.email = email.downcase} #callback before savin
   has_many :recipes
   has_many :likes 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  
  # # unlike laravell the attributes are validated huku
    validates  :name, presence: true, length: {maximum: 50}
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  #this is provided on the net.. it provides a format
    validates :email, presence: true, uniqueness: {case_sensitive: false},
               format: {with: VALID_EMAIL_REGEX}         
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def show
        @user = User.find(params[:id])
        @recipes= @user.recipes.paginate(page: params[:page], per_page: 3) 
    end
    def index
        @user = User.paginate(page: params[:page], per_page: 3)
    end     
end

app/views/user/_form.html.erb
<div class= "row">
    <div class="well col-md-8">
        <%= form_for( @user, html: {multipart: true}) do |f|%> <%#the 'html:' symbol was aadedd after image upload feaat was active%>
            <%=f.label :name%>
            <%=f.text_field :name%>
            
            <%=f.label :email%>
            <%=f.text_field :email%>
            
            <%=f.label :password%>
            <%=f.password_field :password, rows: 10 %>

            <%=f.submit(@user.new_record? ? 'register': 'Edit user', class: "btn btn-success")%> <%# Be make sure not to forget the second"?" "%>
        <%end%>
    </div>
</div>
<%# this is tpo handle page size %>

app/views/user/edit.html.erb
<%= render 'shared/errors' , obj:@user%>
<%= render 'form'%>

app/views/user/index.html.erb
<%= render 'shared/page_title', title: "All Chefs"%>
<div class="row">
<ul class="nav nav-tabs">
    <li >
        <%= link_to "Recipes",recipes_path%>
    </li>
    <li class= "active">
        <%= link_to "Chefs", users_path%>
    </li>
</ul>
    <div class= "col-md-4 col-md-offset-4 center">
        <%= will_paginate%>
    </div>
</div>
<hr/>

<% @user.each do |user| %>
<div class="row">
    <div class= "col-md-4 col-md-offset-4 center">
        <%= link_to gravatar_for(user, size: 200), user_show_path(user)%>
        <p>
            <h5>
                Chef Name: <%=user.name.capitalize%>
            </h5>
        </p>
    </div>
</div>
<% end %>

app/views/user/show.html.erb
<%= render 'shared/page_title', title: 'Chef : '+ @user.name.capitalize %>

<div class= "row">
    <div class= "col-md-4 col-md-offset-4 center ">
    <%= gravatar_for @user, size: 200%>
    <hr/>
    </div>
</div>
<div class= "row">
   <div class= "col-md-4 col-md-offset-4 center">
    <h3><em> Recipes : </em></h3>
    <%= will_paginate @recipes%>
   </div> 
<div>
<% @recipes.each do |recipe| %>
<div class = "row">
    <div class="col-lg-6 well col-lg-offset-3">
        <h4><%= link_to recipe.name,recipe_path(recipe) %> </h4>
        <p><%=  recipe.summary %> </p>
        <p>
            <span class= "quiet">
                <small>
                    Created :  <%= time_ago_in_words(recipe.created_at)%> ago &nbsp 
                </small>
            </span>
            <span class= "quiet">
                <small style="color:green;">
                    Updated : <%= time_ago_in_words(recipe.updated_at)%> ago 
                </small>
            </span>
        </p> 
        
            &nbsp
            <div class= " col-sm-offset-7 col-sm-2">
                <%= button_to [:like, recipe,like: true],style: "background-color: transparent;border: transparent;" do %>
                    <i class = "glyphicon glyphicon-thumbs-up"></i>&nbsp <%= recipe.thumbs_up_counter%>
                <% end  %>
            </div>
                &nbsp&nbsp&nbsp
            <div class = "col-sm-2">
                <%= button_to [:like, recipe, like: false],style: "background-color: transparent;border: transparent;" do %>
                    <i class = "glyphicon glyphicon-thumbs-down"></i>&nbsp  <%= recipe.thumbs_down_counter%>
                    <% end %>
            </div>                 
        </div>
    </div>
    <% end %>